#!/usr/bin/env bash
set -e
 
sudo apt-get build-dep ruby1.9.1
 
wget -c http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p0.tar.gz
tar xzf ruby-2.0.0-p0.tar.gz
cd ruby-2.0.0-p0
 
./configure
make
 
sudo checkinstall -y \
--pkgversion 2.0.0-p0 \
--provides "ruby-interpreter"
