#!/bin/sh

sudo apt-get install -y build-essential git-core
sudo apt-get install -y curl
sleep 30

#bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
#echo '[[ -s "/home/op/.rvm/scripts/rvm" ]] && source "/home/op/.rvm/scripts/rvm"' >> ~/.bashrc
source /home/op/.rvm/scripts/rvm
source ~/.bashrc
sleep 10
type rvm | head -1
sleep 10
rvm install 1.9.3
sleep 10
rvm use --default 1.9.3
